import { db } from "../db";
import { history, type NewHistoryEntry, type HistoryEntry } from "../db/schema";
import { desc, like } from "drizzle-orm";
import { writeFile, mkdir } from "fs/promises";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

// History folder path - relative to project root
const __dirname = dirname(fileURLToPath(import.meta.url));
const HISTORY_DIR = join(__dirname, "records");

// Ensure history directory exists
await mkdir(HISTORY_DIR, { recursive: true });

interface SaveHistoryParams {
  query: string;
  command: string;
  model: string;
  response: string;
  citations?: Array<{ title: string; url: string; date?: string }>;
  promptTokens?: number;
  completionTokens?: number;
  totalTokens?: number;
  durationSeconds?: number;
}

/**
 * Generate a sanitized filename from the query
 */
function generateFilename(query: string, timestamp: Date): string {
  const date = timestamp.toISOString().slice(0, 10); // YYYY-MM-DD
  const time = timestamp.toISOString().slice(11, 19).replace(/:/g, "-"); // HH-MM-SS
  const slug = query
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .slice(0, 50)
    .replace(/-+$/, ""); // Remove trailing dashes

  return `${date}_${time}_${slug}.md`;
}

/**
 * Generate markdown content for the history file
 */
function generateMarkdown(params: SaveHistoryParams, timestamp: Date): string {
  const citationsMarkdown = params.citations?.length
    ? `\n## 📚 Sources\n\n${params.citations
        .map(
          (c, i) =>
            `${i + 1}. [${c.title}](${c.url})${c.date ? ` - ${c.date}` : ""}`,
        )
        .join("\n")}\n`
    : "";

  const statsMarkdown = params.totalTokens
    ? `\n## 📊 Statistics\n
| Metric | Value |
|--------|-------|
| Total Tokens | ${params.totalTokens} |
| Prompt Tokens | ${params.promptTokens} |
| Completion Tokens | ${params.completionTokens} |
| Duration | ${params.durationSeconds?.toFixed(2)}s |
| Model | \`${params.model}\` |
| Command | \`${params.command}\` |
`
    : "";

  return `# ${params.query}

> **Query executed on ${timestamp.toLocaleString()}**

---

## 💬 Response

${params.response}
${citationsMarkdown}${statsMarkdown}
---

*Generated by [pplx-cli](https://github.com/perplexity/pplx-cli)*
`;
}

/**
 * Save a history entry to the database and create markdown file
 */
export async function saveHistory(
  params: SaveHistoryParams,
): Promise<HistoryEntry> {
  const timestamp = new Date();
  const filename = generateFilename(params.query, timestamp);
  const filepath = join(HISTORY_DIR, filename);

  // Generate and write markdown file
  const markdown = generateMarkdown(params, timestamp);
  await writeFile(filepath, markdown, "utf-8");

  // Save to database
  const entry: NewHistoryEntry = {
    timestamp: timestamp.getTime(),
    query: params.query,
    command: params.command,
    model: params.model,
    response: params.response,
    citations: params.citations ? JSON.stringify(params.citations) : null,
    promptTokens: params.promptTokens,
    completionTokens: params.completionTokens,
    totalTokens: params.totalTokens,
    durationSeconds: params.durationSeconds,
  };

  const result = await db.insert(history).values(entry).returning();
  const inserted = result[0];
  if (!inserted) {
    throw new Error("Failed to insert history entry");
  }

  console.log(`📁 Saved to: ${filepath}`);
  return inserted;
}

/**
 * Get recent history entries
 */
export async function getRecentHistory(limit = 10): Promise<HistoryEntry[]> {
  return db
    .select()
    .from(history)
    .orderBy(desc(history.timestamp))
    .limit(limit);
}

/**
 * Search history by query text
 */
export async function searchHistory(
  searchTerm: string,
): Promise<HistoryEntry[]> {
  return db
    .select()
    .from(history)
    .where(like(history.query, `%${searchTerm}%`))
    .orderBy(desc(history.timestamp))
    .limit(50);
}

/**
 * Get all history entries
 */
export async function getAllHistory(): Promise<HistoryEntry[]> {
  return db.select().from(history).orderBy(desc(history.timestamp));
}
